sonar.projectKey=maksimtech_patchradar
sonar.organization=maksimtech
sonar.projectName=PatchRadar
sonar.python.version=3.11, 3.12, 3.13, 3.14
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*
sonar.exclusions=**/__pycache__/**,**/*.pyc

sonar.coverage.exclusions=**/*
